### ISSUE TITLE
To-dos status

### ISSUE THREAD

**Issue by d-packs** [stamat/youtube-background#11] opened 2020-04-30 20:21 UTC
I was wondering if you plan to revisit the tasks on your to-do list and finish some of the points you've planned to implement:
![capture-200430-231911](https://user-images.githubusercontent.com/33980111/80755323-41b50300-8b39-11ea-9ce9-d482368cb603.png)
 
Specifically I'm interested to know about the pause-while-hidden features.

**Comment by stamat** [comment] 2020-05-07 14:23
This is sort of a duplicate of #10
So let's move the discussion there?

Thanks!

**Closed as completed by stamat** 2020-05-07 14:23 UTC
